# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='PublicKey',
            field=models.CharField(max_length=4096),
        ),
    ]
