# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180423_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='id',
        ),
        migrations.AlterField(
            model_name='cert',
            name='PublicKey',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='cert',
            name='SerialNumber',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='cert',
            name='Subject',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
